apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookgate.name" . }}-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "bookgate.name" . }}-api
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: {{ .Values.apiService.port }}
