apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookgate.name" . }}-chat-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "bookgate.name" . }}-chat
  ports:
    - port: {{ .Values.chatService.port }}
      targetPort: {{ .Values.chatService.port }}
