apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookgate.name" . }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "bookgate.name" . }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
