apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiService.serviceAccount.name }}
  namespace: {{ include "bookgate.namespace" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.apiService.serviceAccount.roleArn | quote }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bookgate.name" . }}-secret
  namespace: {{ include "bookgate.namespace" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: DATABASE_URL
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: SECRET_KEY
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: ADMIN_PASSWORD
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: OPENAI_API_KEY
