apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookgate.name" . }}-api-service
  namespace: {{ include "bookgate.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "bookgate.name" . }}-api
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: {{ .Values.apiService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookgate.name" . }}-chat-service
  namespace: {{ include "bookgate.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "bookgate.name" . }}-chat
  ports:
    - port: {{ .Values.chatService.port }}
      targetPort: {{ .Values.chatService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookgate.name" . }}-frontend
  namespace: {{ include "bookgate.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "bookgate.name" . }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
