apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops-bot.name" . }}
  namespace: {{ include "aiops-bot.namespace" . }}
  labels:
    {{- include "aiops-bot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aiops-bot.selectorLabels" . | nindent 4 }}
