# values-dev.yaml — dev environment configuration

ecr:
  registry: "392423995152.dkr.ecr.us-east-1.amazonaws.com"

image:
  tag: "06edc92"

serviceAccount:
  roleArn: "arn:aws:iam::392423995152:role/bookgate-eks-aiops-bot-role"

bedrock:
  roleArn: "arn:aws:iam::400071840696:role/bot-assume-role"
  region: "us-east-1"

externalSecrets:
  enabled: true
  remoteSecretName: "bookgate/dev/aiops-bot-secrets"
